name: Mirror to protovladyts

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history (no creds)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # <- clave

      - name: Remove default GitHub token header
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true

      - name: Configure git identity
        run: |
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

      - name: Add target remote (authenticated)
        env:
          USERNAME: ${{ secrets.TARGET_USER_PROTOVLADYTS }}      # protovladyts
          TOKEN:    ${{ secrets.TARGET_REPO_TOKEN_PROTOVLADYTS }} # PAT fine-grained con write
        run: |
          git remote add target https://${USERNAME}:${TOKEN}@github.com/protovladyts/silalunahablara.git
          git remote -v

      - name: Push main and tags (force mirror)
        run: |
          git push target main --force
          git push target --tags --force
